name: Build And Deploy
on:
  push:
    branches: [ "main" ] # Build and deploy on pushes to the main branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 23 # Use a Node.js version compatible with your Vue.js project

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Directory containing the built files
